# Generated by Django 5.0.2 on 2024-05-18 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('flight_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crew_type', models.CharField(choices=[('flight', 'Flight Crew'), ('cabin', 'Cabin Crew')], max_length=6)),
                ('seniority_level', models.CharField(max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_members', to='backend.flight')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.crewmember')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_crew', to='backend.flight')),
            ],
        ),
    ]
