# Generated by Django 5.0.2 on 2024-05-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmember',
            name='attendant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewmember',
            name='pilot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
