# Generated by Django 5.0.2 on 2024-05-06 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passenger_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=255)),
                ('seat_type', models.CharField(max_length=20)),
                ('seat_number', models.CharField(max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PassengerInfo.flights')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PassengerInfo.passengers')),
            ],
        ),
    ]
