# Generated by Django 5.0.2 on 2024-05-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightInfo', '0003_alter_flights_flight_duration'),
        ('PassengerInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightInfo.flights'),
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
    ]
