# Generated by Django 5.0.2 on 2024-05-15 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CabinCrew',
            fields=[
                ('attendant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('known_languages', models.CharField(max_length=200)),
                ('attendant_type', models.CharField(choices=[('chief', 'Chief'), ('regular', 'Regular'), ('chef', 'Chef')], max_length=10)),
                ('vehicle_restrictions', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DishRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('chef', models.ForeignKey(limit_choices_to={'attendant_type': 'chef'}, on_delete=django.db.models.deletion.CASCADE, to='CabinCrewInfo.cabincrew')),
            ],
        ),
    ]
