# Generated by Django 5.0.2 on 2024-05-06 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=255)),
                ('number_of_seats', models.IntegerField()),
                ('seating_plan', models.CharField(max_length=255)),
                ('crew_limit', models.IntegerField()),
                ('passenger_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('flight_date', models.DateTimeField()),
                ('flight_duration', models.TimeField()),
                ('flight_distance', models.FloatField()),
                ('source_country', models.CharField(max_length=255)),
                ('source_city', models.CharField(max_length=255)),
                ('source_airport_name', models.CharField(max_length=255)),
                ('source_airport_code', models.CharField(max_length=3)),
                ('destination_country', models.CharField(max_length=255)),
                ('destination_city', models.CharField(max_length=255)),
                ('destination_airport_name', models.CharField(max_length=255)),
                ('destination_airport_code', models.CharField(max_length=3)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightInfo.vehicletypes')),
            ],
        ),
    ]
