# Generated by Django 5.0.2 on 2024-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='shared_flight',
            field=models.BooleanField(default=False),
        ),
    ]
