# Generated by Django 5.0.2 on 2024-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightInfo', '0004_flightlocations'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flightlocations',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flightlocations',
            name='airport_code',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightlocations',
            name='airport_name',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
