# Generated by Django 5.0.2 on 2024-05-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('pilot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('known_languages', models.CharField(max_length=200)),
                ('vehicle_restriction', models.CharField(max_length=100)),
                ('allowed_range', models.PositiveIntegerField()),
                ('seniority_level', models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior'), ('trainee', 'Trainee')], max_length=10)),
            ],
        ),
    ]
